/** A "Did you know?" line for each species' Fishpedia page. Real facts, kept short for young readers. */
export const FISH_FACTS: Record<string, string> = {
  goldfish: 'Goldfish can see more colours than people can, even ultraviolet light.',
  guppy: 'Mother guppies give birth to live babies instead of laying eggs.',
  'neon-tetra': "A neon tetra's stripe fades at night while it rests, then brightens again in the morning.",
  'zebra-danio': 'Zebra danios can regrow their fins and even parts of their heart, so scientists study them to learn about healing.',
  'cory-catfish': 'Cory catfish sometimes dart up to the surface to gulp a quick breath of air.',
  platy: 'Platies come from rivers in Mexico and Central America, and have live babies just like guppies.',
  molly: 'Some mollies are happy in fresh water, salty sea water, or anything in between.',
  damselfish: "Damselfish are tiny but brave: they'll chase much bigger fish away from their patch of reef.",
  clownfish: 'Clownfish wear a special slime that stops their anemone home from stinging them.',
  swordtail: 'Only boy swordtails grow the long "sword" on their tail.',
  rainbowfish: 'Many rainbowfish get brighter as they grow up. Young ones can look quite plain!',
  betta: 'Bettas have a special organ that lets them breathe air from the surface.',
  angelfish: 'Angelfish parents work as a team, guarding their eggs and fanning them with their fins.',
  oscar: 'Oscars can learn to recognise the person who feeds them.',
  discus: "Baby discus feed on a special slime from their parents' skin.",
  pufferfish: 'Pufferfish puff up by gulping lots of water, which turns them into a big spiky ball.',
  parrotfish: 'Parrotfish crunch on coral, and lots of the white sand on tropical beaches came out of them!',
  koi: 'Koi can live a very long time. Some are said to have lived for more than 100 years.',
  glowfin: 'Real deep-sea fish can make their own light. It is called bioluminescence.',
  lionfish: "A lionfish's frilly fins look pretty, but its spines can sting, so other fish keep their distance.",
  mandarin: 'Mandarin dragonets have no scales. A coat of slimy mucus helps keep hungry predators away.',
  'reef-shark': 'Sharks have no bones. Their skeletons are made of cartilage, like the tip of your nose.',
  arowana: 'Arowanas can leap right out of the water to snatch bugs from branches.',
  'nerite-snail': "Nerite snail eggs won't hatch in fresh water, so these snails never take over a tank.",
  'cherry-shrimp': 'Cherry shrimp wriggle out of their whole shell as they grow, then hide until the new one hardens.',
  'moon-jelly': 'Moon jellies have no brain, no heart and no bones. They are almost all water!',
  seahorse: 'Seahorse dads carry the eggs in a pouch on their tummy until the babies hatch.',
  axolotl: 'Axolotls can regrow a lost leg, and even parts of their heart and brain.',
  'regal-tang': 'Regal tangs have a sharp spine by their tail that they can flick out to protect themselves.',
  'moorish-idol': 'Moorish idols trail a long white fin behind them like a streamer.',
  octopus: 'An octopus has three hearts and blue blood.',
  flowerhorn: "You won't find flowerhorns in the wild. People bred them from other cichlid fish.",
  'manta-ray': 'Manta rays have one of the biggest brains of any fish.',
  'starry-pleco': 'Plecos have a sucker mouth that lets them cling to rocks and scrape off algae.',
  'sea-turtle': 'Sea turtles swim back to the very beach where they hatched to lay their own eggs.',
  'emperor-angelfish': 'Young emperor angelfish are blue with white rings, and change to stripes as they grow up.',
  'comet-goldfish': 'Comet goldfish were first bred in America in the 1800s, from ordinary pond goldfish.',
  'golden-orfe': 'Golden orfes swim near the surface in groups and love to snap up insects that land on the water.',
  'butterfly-koi': 'Butterfly koi have long, flowing fins that keep growing for years as the fish gets older.',
  'dragon-koi': 'An old legend says a koi that swims up a great waterfall becomes a dragon. This one made it!',
}
